### ISSUE TITLE
make plugin installable by composer

### ISSUE THREAD

**Issue by gearsdigital** [medienbaecker/kirby-autoresize#3]
It would be very nice if the plugin would be installable by composer.

`composer require  medienbaecker/kirby-autoresize` fails right now:

> Could not find a matching version of package medienbaecker/kirby-autoresize. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable)

https://getkirby.com/docs/guide/plugins/plugin-setup-basic#the-composer-json

Thanks in advance :)

**Comment by gearsdigital** [comment]
Closed without any comment 😢

**Comment by medienbaecker** [comment]
Does the release not work for you? Unfortunately I don't use composer, but I thought adding a stable release would be enough 😬

**Comment by gearsdigital** [comment]
Nah, it works totally fine! I just dislike the manual effort to _download_, _unpack_ and _copy_ stuff 🙃 I thought, because you've provided a composer.json, it might be doable... but nevermind.

Thanks for this plugin!

**Comment by hariioom** [comment]
I would love being able to use composer, too. It's so convenient...

**Comment by medienbaecker** [comment]
What exactly is missing for you to use composer?

**Comment by hariioom** [comment]
I get the same error as @gearsdigital. I think composer.json might be something like `require": {
        "getkirby/composer-installer": "^1.1"
    }`(exmaple in the kirby docs for composer).

> It would be very nice if the plugin would be installable by composer.
> 
> `composer require medienbaecker/kirby-autoresize` fails right now:
> 
> > Could not find a matching version of package medienbaecker/kirby-autoresize. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable)
> 
> https://getkirby.com/docs/guide/plugins/plugin-setup-basic#the-composer-json
> 
> Thanks in advance :)

**Comment by medienbaecker** [comment]
Is see. I just added `require` and `"type": "kirby-plugin"` to the composer.json.
Please let me know if it works for you.

**Comment by hariioom** [comment]
Thanks for the quick update @medienbaecker. Unfortunately still not working for me. Checking  your other repository (kirby-modules) I noticed, that kirby-modules has a release tab (v. 0.6), whereas autoresize doesn't. Maybe that is the cause, but I can only guess...

**Comment by medienbaecker** [comment]
@hariioom Thanks for checking! This repo has releases, too. Maybe it takes some time for it to work? 🤔

**Comment by hariioom** [comment]
@medienbaecker Could it be, that autoresize is not yet registred with [packagist](https://packagist.org/)? There I can only find medienbaecker/kirby-modules ...

**Comment by medienbaecker** [comment]
@lucadorata I just submitted the repository to packagist. It should work now :)

**Comment by lucadorata** [comment]
@medienbaecker worked like a charm now, thanks a lot!

**Comment by KPLehmann** [comment]
Would be awesome to add `composer require medienbaecker/kirby-autoresize` to the readme file! 😄

**Comment by medienbaecker** [comment]
> Would be awesome to add `composer require medienbaecker/kirby-autoresize` to the readme file! 😄

✅

**Comment by MathiasGmeiner** [comment]
I think you have a typo in `composer require`.  At least the package on packagist is called "autoresize" not "kirby-autoresize".

`composer require medienbaecker/autoresize ` is working for me!

**Comment by medienbaecker** [comment]
> `composer require medienbaecker/autoresize ` is working for me!

@MathiasGmeiner Thanks for letting me know. I updated the README.
