### ISSUE TITLE
Ability to prevent resizing on specific pages/templates

### ISSUE THREAD

**Issue by ldanielswakman** [medienbaecker/kirby-autoresize#4]
Although the image resizing features is very useful on most pages, there might be occasions you want to allow users to upload in higher resolution, for specific use-cases. What about having an `ignore_page` (Array) or `ignore_template` (Array) setting in the config file?

**Comment by medienbaecker** [comment]
I added the options in a [separate branch](https://github.com/medienbaecker/kirby-autoresize/tree/feature/options).
Unfortunately further development is halted because if this issue: https://github.com/getkirby/kirby/issues/2343

**Comment by ldanielswakman** [comment]
Great to see, thanks for the quick response! Let's hope the bug gets resolved soon
