### ISSUE TITLE
Error when replacig an image

### ISSUE THREAD

**Issue by tkeil69575** [medienbaecker/kirby-autoresize#5]
The autocrop works fine for new images, but when I try to replace an existing image I get

Argument 2 passed to Kirby\Cms\App::trigger() must be of the type array, object given, 
called in /rootpath/plugins/autoresize/index.php on line 

Any ideas how to fix?

**Comment by medienbaecker** [comment]
Kirby 3.4 changed the way triggers work.
I just released [Autoresize 2.0](https://github.com/medienbaecker/kirby-autoresize/releases/tag/2.0) with Kirby 3.4 compatibility and some new options (`maxHeight`, `excludeTemplates` and `excludePages`)

I hope this fixes the issue. Please let me know if it's still not working for you.
