### ISSUE TITLE
Cannot redeclare autoresize() (previously declared in...

### ISSUE THREAD

**Issue by bldevuid798** [medienbaecker/kirby-autoresize#8]
This plugin has always worked, but now seems to throw an exception with Kirby 3.6. The error message is: Cannot redeclare autoresize() (previously declared in \site\plugins\autoresize\index.php:3)

**Comment by medienbaecker** [comment]
Which version of the plugin do you use? I had to make some adjustments for 3.6 but it seems to work just fine now.

**Comment by bldevuid798** [comment]
On closer inspection it's nothing to do with the plugin - it's the theme that wasn't updated to work with the new version. Thanks and closing.
